/**
 * src/services/auth.service.ts — Authentication business logic.
 */

import { prisma } from '../prisma/prisma.client';
import { hashPassword, verifyPassword, generateRandomPassword } from '../utils/bcrypt';
import { signAccessToken, signRefreshToken, verifyRefreshToken } from '../utils/jwt';
import { AuthInvalidCredentials, AuthForbidden } from '../utils/errors';
import { loginSchema, passwordSchema, Role } from '@unify/shared-types';
import { auditService } from './audit.service';
import { AuditActionType } from '@unify/shared-types';

export const authService = {
  async login(username: string, password: string) {
    const parsed = loginSchema.parse({ username, password });

    const user = await prisma.user.findUnique({
      where: { username: parsed.username },
      include: { department: true },
    });

    if (!user || !user.isActive) {
      throw AuthInvalidCredentials();
    }

    const passwordOk = await verifyPassword(parsed.password, user.passwordHash);
    if (!passwordOk) {
      throw AuthInvalidCredentials();
    }

    await prisma.user.update({
      where: { id: user.id },
      data: { lastLoginAt: new Date() },
    });

    await auditService.log({
      actorId: user.id,
      actorRole: user.role,
      actionType: AuditActionType.LOGIN,
      targetEntityType: 'User',
      targetEntityId: user.id,
    });

    const accessToken = signAccessToken({
      userId: user.id,
      username: user.username,
      role: user.role,
      departmentId: user.departmentId,
    });
    const refreshToken = signRefreshToken({
      userId: user.id,
      tokenVersion: 1,
    });

    return {
      accessToken,
      refreshToken,
      role: user.role,
      onboardingComplete: user.onboardingComplete,
      user: {
        id: user.id,
        username: user.username,
        firstName: user.firstName,
        lastName: user.lastName,
        role: user.role,
        themePreference: user.themePreference,
        darkMode: user.darkMode,
        departmentId: user.departmentId,
      },
    };
  },

  async refresh(refreshToken: string) {
    const payload = verifyRefreshToken(refreshToken);
    const user = await prisma.user.findUnique({
      where: { id: payload.userId },
    });
    if (!user || !user.isActive) {
      throw AuthForbidden('کاربر غیرفعال است');
    }
    const accessToken = signAccessToken({
      userId: user.id,
      username: user.username,
      role: user.role,
      departmentId: user.departmentId,
    });
    return { accessToken };
  },

  async changePassword(userId: string, currentPassword: string, newPassword: string) {
    passwordSchema.parse(newPassword);
    const user = await prisma.user.findUnique({ where: { id: userId } });
    if (!user) throw AuthInvalidCredentials();
    const ok = await verifyPassword(currentPassword, user.passwordHash);
    if (!ok) throw AuthInvalidCredentials('رمز عبور فعلی اشتباه است');

    const newHash = await hashPassword(newPassword);
    await prisma.user.update({
      where: { id: userId },
      data: { passwordHash: newHash },
    });

    await auditService.log({
      actorId: userId,
      actorRole: user.role,
      actionType: AuditActionType.PASSWORD_RESET,
      targetEntityType: 'User',
      targetEntityId: userId,
      context: { source: 'SELF_SERVICE' },
    });
  },

  async resetPassword(actorId: string, actorRole: Role, targetUserId: string, newPassword?: string) {
    passwordSchema.parse(newPassword || 'Temp1234!');
    const finalPassword = newPassword || generateRandomPassword(12);
    const hash = await hashPassword(finalPassword);

    await prisma.user.update({
      where: { id: targetUserId },
      data: { passwordHash: hash },
    });

    await prisma.passwordResetRequest.create({
      data: {
        userId: targetUserId,
        performedBy: actorId,
      },
    });

    await auditService.log({
      actorId,
      actorRole,
      actionType: AuditActionType.PASSWORD_RESET,
      targetEntityType: 'User',
      targetEntityId: targetUserId,
      context: { source: 'OWNER_RESET', autoGenerated: !newPassword },
    });

    return { newPassword: finalPassword };
  },

  async logout(userId: string, role: Role) {
    await auditService.log({
      actorId: userId,
      actorRole: role,
      actionType: AuditActionType.LOGOUT,
      targetEntityType: 'User',
      targetEntityId: userId,
    });
  },
};
