#!/usr/bin/env bash
# scripts/audit.sh — Comprehensive document compliance audit.

set -e
cd "$(dirname "$0")/.."

OK="✓"
NO="✗"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         COMPREHENSIVE DOCUMENT COMPLIANCE AUDIT            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "─── PROJECT STATS ───"
echo "  Total files:           $(find . -type f -not -path "*/node_modules/*" -not -path "./storage/*" -not -path "./.git/*" | wc -l)"
echo "  TS/TSX files:          $(find . -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.prisma" \) -not -path "*/node_modules/*" | wc -l)"
echo "  TS LOC:                $(find . -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.prisma" \) -not -path "*/node_modules/*" -exec wc -l {} + | tail -1 | awk '{print $1}')"
echo "  Frontend pages:        $(find apps/web/src/app -name "page.tsx" | wc -l)"
echo "  API routes:            $(ls apps/api/src/routes/*.ts | wc -l)"
echo "  Tests:                 $(find tests -name '*.test.ts' -o -name '*.spec.ts' 2>/dev/null | wc -l)"
echo "  TODO/'any' placeholders: $(grep -rE 'TODO|FIXME|as any' --include='*.ts' --include='*.tsx' --include='*.prisma' apps/ packages/ prisma/ 2>/dev/null | wc -l)"
echo ""

check() {
  local label="$1"
  local cmd="$2"
  if eval "$cmd" >/dev/null 2>&1; then
    echo "  [$OK] $label"
  else
    echo "  [$NO] $label"
  fi
}

echo "═══════════════════════════════════════════════════════════════"
echo "GOLDEN DOC §1 — SYSTEM SETTINGS"
echo "═══════════════════════════════════════════════════════════════"
check "§1.1.1 Logo upload"                       "grep -q '/logo' apps/api/src/routes/admin.routes.ts"
check "§1.1.2 Color Themes picker"               "test -f apps/web/src/components/shared/ThemePicker.tsx"
check "§1.1.2 Dark Mode"                          "grep -q 'darkMode' apps/web/src/lib/stores/theme.store.ts"
check "§1.2.1 Credentials format"                "grep -q 'دانشجویی' 'apps/web/src/app/(auth)/login/page.tsx'"
check "§1.2.2 Password lifecycle"                "grep -q 'generateRandomPassword' apps/api/src/services/auth.service.ts"
check "§1.2.3 In-person password reset"          "grep -q 'OWNER_RESET' apps/api/src/services/auth.service.ts"
check "§1.2.4 Mandatory onboarding"              "grep -q 'onboardingComplete' apps/api/src/middleware/rbac.middleware.ts"
check "§1.2.5 Profile Photo upload + display"    "test -f apps/web/src/components/shared/PhotoUpload.tsx && grep -q 'AvatarImage' apps/web/src/components/ui/avatar.tsx"
check "§1.2.6 Banning + audit"                   "grep -q 'USER_BANNED' apps/api/src/routes/admin.routes.ts"
check "§1.3.1 Pushe + Socket.io"                 "grep -iq 'pushe' apps/api/src/services/notification.service.ts && grep -q 'SocketBootstrap' apps/web/src/components/shared/SocketBootstrap.tsx"
check "§1.3.2 Mute per-spec"                     "grep -q 'NotificationPreference' apps/api/src/routes/notification.routes.ts"
check "§1.4.1 Excel import/export"               "grep -q 'ExcelJS' apps/api/src/services/excel.service.ts"
check "§1.4.2 Archive Dropdown on Dashboard"      "test -f apps/web/src/components/student/ArchiveDropdown.tsx"
check "§1.4.3 Audit logging"                     "grep -q 'auditService' apps/api/src/utils/audit-logger.ts"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "GOLDEN DOC §2 — STUDENT APP"
echo "═══════════════════════════════════════════════════════════════"
check "§2.1.1 Dashboard w/ course cards"          "test -f 'apps/web/src/app/(app)/student/dashboard/page.tsx'"
check "§2.1.1 Archive Dropdown 'top of page'"   "grep -q 'ArchiveDropdown' 'apps/web/src/app/(app)/student/dashboard/page.tsx'"
check "§2.1.2 Card color customization"          "test -f apps/web/src/components/student/CardColorPicker.tsx"
check "§2.1.2 Footer (Resources/Tg/Details)"     "grep -q 'CourseDetailsModal' 'apps/web/src/app/(app)/student/dashboard/page.tsx'"
check "§2.1.2 Final exam date on card"           "grep -q 'finalExamDate' 'apps/web/src/app/(app)/student/dashboard/page.tsx'"
check "§2.1.3 Critical Alert banner"             "test -f apps/web/src/components/student/CriticalAlertBanner.tsx"
check "§2.1.3 Cancelled-spec 7-day banner"       "test -f apps/web/src/components/student/CancelledNoticeBanner.tsx"
check "§2.2.1 Phase A search + temp list"        "test -f 'apps/web/src/app/(app)/student/scheduler/page.tsx'"
check "§2.2.1 Min credit (NORMAL=12)"             "grep -q 'limit.min' apps/api/src/services/scheduler.service.ts"
check "§2.2.1 Final Semester dialog"            "test -f apps/web/src/components/student/FinalSemesterDialog.tsx"
check "§2.2.1 Submit Final Registration"         "grep -q 'submitFinalList' apps/api/src/services/scheduler.service.ts"
check "§2.2.1 Grace Period (24h wipe)"            "grep -q 'grace-period-wipe' apps/api/src/jobs/job-runner.ts"
check "§2.2.3 Phase C Flip Animation (Framer)"   "test -f apps/web/src/components/student/ExamScheduleFlip.tsx"
check "§2.3 Resource Hub"                        "test -f 'apps/web/src/app/(app)/student/resources/page.tsx'"
check "§2.3.5 File versioning"                    "grep -q 'uploadNewVersion' apps/api/src/services/resource.service.ts"
check "§2.4 Inbox unified"                        "test -f 'apps/web/src/app/(app)/student/inbox/page.tsx'"
check "§2.4.1 Visual source differentiation"      "grep -q 'SOURCE_CONFIG' 'apps/web/src/app/(app)/student/inbox/page.tsx'"
check "§2.4.3 Edited timestamp display"          "grep -q 'ویرایش شده در' 'apps/web/src/app/(app)/student/inbox/page.tsx'"
check "§2.4.3 XSS-safe content rendering"         "grep -q 'SafeText' 'apps/web/src/app/(app)/student/inbox/page.tsx'"
check "§2.5 Tickets"                             "test -f 'apps/web/src/app/(app)/student/tickets/page.tsx'"
check "§2.5.3 48h auto-escalation"                "grep -q 'addTicketEscalationJob' apps/api/src/services/ticket.service.ts"
check "§2.6.1 Curriculum tree view"              "test -f apps/web/src/components/student/CurriculumTreeView.tsx"
check "§2.6.1 Prerequisite popup-on-click"       "test -f apps/web/src/components/student/CoursePrereqPopup.tsx"
check "§2.6.2 Forms Repository"                  "test -f 'apps/web/src/app/(app)/student/utilities/page.tsx'"
check "§2.6.3 Academic Calendar"                 "grep -q 'AcademicCalendar' apps/api/src/routes/calendar.routes.ts"
check "§2.6.4 Assignment Tracker"                "grep -q 'AssignmentTask' apps/api/src/routes/assignment.routes.ts"
check "§2.6.5 Notice Board + FAQ"                "test -f apps/web/src/components/student/CourseDetailsModal.tsx"
check "§2.6.6 Dedicated /student/notices"        "test -f 'apps/web/src/app/(app)/student/notices/page.tsx'"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "GOLDEN DOC §3 — STAFF PANELS"
echo "═══════════════════════════════════════════════════════════════"
check "§3.1 Settings page (all roles)"           "test -f 'apps/web/src/app/(app)/settings/page.tsx'"
echo "  Professor pages:        $(find apps/web/src/app/\(app\)/professor -name page.tsx 2>/dev/null | wc -l)/8"
echo "  Expert pages:            $(find apps/web/src/app/\(app\)/expert -name page.tsx 2>/dev/null | wc -l)/8"
echo "  Head pages:              $(find apps/web/src/app/\(app\)/head -name page.tsx 2>/dev/null | wc -l)/2"
echo "  Admin pages:             $(find apps/web/src/app/\(app\)/admin -name page.tsx 2>/dev/null | wc -l)/8"
echo "  Owner pages:             $(find apps/web/src/app/\(app\)/owner -name page.tsx 2>/dev/null | wc -l)/6"
check "§3.5.7 Final Note Approval + fallback"    "grep -q 'FALLBACK_DAYS' 'apps/web/src/app/(app)/admin/files/page.tsx'"
check "§3.5.8 Admin file management"             "test -f 'apps/web/src/app/(app)/admin/files/page.tsx'"
check "§3.6.2 Bulk user upload + template"       "test -f scripts/excel-templates/user-bulk-upload-template.xlsx"
check "§3.6.3 Password reset"                    "grep -q 'reset-password' apps/api/src/routes/owner.routes.ts"
check "§3.6.4 Audit log access"                  "test -f apps/api/src/routes/audit.routes.ts"
check "§3.6.5 Analytics w/ download counts"       "grep -q 'ResourceDownload\|byCourse' apps/api/src/routes/analytics.routes.ts"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "AGENT GUIDE COMPLIANCE"
echo "═══════════════════════════════════════════════════════════════"
check "Rule 1 (no TODO/'any')"                    "[ $(grep -rE 'TODO|FIXME|as any' --include='*.ts' --include='*.tsx' --include='*.prisma' apps/ packages/ prisma/ 2>/dev/null | wc -l) = 0 ]"
check "Rule 7 (audit append-only)"               "grep -q 'attemptType' apps/api/src/utils/audit-logger.ts"
check "D1: Same-course warning"                  "grep -q 'گروه دیگر' apps/api/src/services/scheduler.service.ts"
check "D2: Ratings preserved on version"         "grep -q 'ratingCount' apps/api/src/services/resource.service.ts"
check "D3: Placeholder on delete w/ replies"      "grep -q 'PLACEHOLDER_CONTENT' apps/api/src/services/message.service.ts"
check "D4: Critical alerts bypass mute"          "grep -q 'bypassMute' apps/api/src/services/notification.service.ts"
check "D5: Deleted spec + 7-day notice"          "grep -q 'CancelledSpecificationNotice' prisma/schema.prisma"
check "D6: 3 ticket images max"                  "grep -q 'maxTicketImages' apps/api/src/middleware/upload.middleware.ts"
check "D9: Technical → Admin direct"             "grep -q 'TECHNICAL' apps/api/src/services/ticket.service.ts"
check "D10: Password complexity"                  "grep -q 'passwordSchema' packages/shared-types/src/zod-schemas.ts"
check "D11: Scalability (10k concurrent)"         "grep -q 'connection_limit' .env.example"
check "D12: Cancelled-notice TTL cleanup"         "grep -q 'cleanupQueue' apps/api/src/jobs/job-runner.ts"
check "§6.3 Golden Schedule algorithm"            "grep -q 'backtrack\|memoOverlap' apps/api/src/services/scheduler.service.ts"
check "§6.6 BullMQ 4 queues"                      "grep -q 'ticketEscalationQueue' apps/api/src/jobs/job-runner.ts && grep -q 'cleanupQueue' apps/api/src/jobs/job-runner.ts"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "NON-FUNCTIONAL REQUIREMENTS (§F.1-F.6)"
echo "═══════════════════════════════════════════════════════════════"
check "§F.1 Upload progress indicator"            "test -f apps/web/src/components/shared/UploadProgressBar.tsx"
check "§F.1 Realtime <5s (Socket.io)"             "test -f apps/web/src/components/shared/SocketBootstrap.tsx"
check "§F.2 CSRF protection"                      "grep -q 'X-CSRF-Token' apps/web/src/lib/api-client.ts && grep -q 'csrfProtection' apps/api/src/middleware/csrf.middleware.ts"
check "§F.2 Helmet"                              "grep -q \"helmet('\" apps/api/src/app.ts"
check "§F.2 Bcrypt cost 12"                       "grep -q 'BCRYPT_COST_FACTOR=12' .env.example"
check "§F.2 XSS sanitization (DOMPurify)"         "test -f apps/web/src/lib/sanitize.tsx"
check "§F.3 Backup script"                        "test -f scripts/backup.sh && test -f scripts/restore.sh"
check "§F.4 Skip-to-main link"                    "test -f apps/web/src/components/shared/SkipToMain.tsx"
check "§F.4 Keyboard shortcuts"                   "test -f apps/web/src/components/shared/KeyboardShortcuts.tsx"
check "§F.5 Mobile responsive sidebar"            "grep -q 'md:hidden\|md:mr-64' apps/web/src/components/shared/AppShell.tsx"
check "§F.6 Pool tuning"                          "grep -q 'connection_limit=50' .env.example"
check "§F.6 Standalone jobs process"              "test -f apps/api/src/jobs/standalone.ts"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TEST COVERAGE"
echo "═══════════════════════════════════════════════════════════════"
echo "  Total test files: $(find tests -name '*.test.ts' -o -name '*.spec.ts' 2>/dev/null | wc -l)"
echo "  API tests:        $(find tests/api -name '*.test.ts' 2>/dev/null | wc -l)"
echo "  E2E tests:        $(find tests/e2e -name '*.spec.ts' 2>/dev/null | wc -l)"
echo "  Load tests:       $(find tests/load -name '*.js' 2>/dev/null | wc -l)"
echo ""
for test in auth.test.ts golden-schedule.test.ts ticket-escalation.test.ts message-decision3.test.ts sanitization.test.ts concurrency-pool.test.ts declision-compliance.test.ts; do
  check "  $test" "test -f tests/api/$test"
done
check "  critical-flows.spec.ts" "test -f tests/e2e/critical-flows.spec.ts"
check "  api-load-test.js"   "test -f tests/load/api-load-test.js"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "DOCUMENTATION"
echo "═══════════════════════════════════════════════════════════════"
check "README.md"                                "test -f README.md"
check "docs/USER_GUIDE.md"                        "test -f docs/USER_GUIDE.md"
check "scripts/README.md"                        "test -f scripts/README.md"
check "tests/load/README.md"                     "test -f tests/load/README.md"
check "OpenAPI spec"                             "test -f apps/api/src/routes/openapi.routes.ts"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "AUDIT COMPLETE — All items checked."
echo "═══════════════════════════════════════════════════════════════"
